import { NextRequest } from "next/server";
import { PublicKey } from "@solana/web3.js";
import nacl from "tweetnacl";
import bs58 from "bs58";
import crypto from "crypto";

const NONCE_EXPIRY_MS = 5 * 60 * 1000; // 5 minutes

// In-memory active nonce store (with timestamp)
const activeNonces = new Map<string, number>();

/**
 * Generate a cryptographically secure random nonce for admin authentication challenge
 */
export function generateAdminNonce(walletAddress: string): string {
  // Clean up expired nonces
  const now = Date.now();
  for (const [key, timestamp] of activeNonces.entries()) {
    if (now - timestamp > NONCE_EXPIRY_MS) {
      activeNonces.delete(key);
    }
  }

  const randomBytes = crypto.randomBytes(16).toString("hex");
  const nonce = `ilyrium_admin_auth_${walletAddress}_${randomBytes}_${now}`;
  activeNonces.set(nonce, now);
  return nonce;
}

/**
 * Validates whether an incoming request satisfies all admin security criteria:
 * 1. Admin Master Passphrase
 * 2. Whitelisted Admin Wallet Address
 * 3. Valid ED25519 Solana Signature of an active challenge nonce
 */
export async function verifyAdminRequest(request: NextRequest): Promise<{
  authorized: boolean;
  wallet?: string;
  error?: string;
}> {
  const adminSecret = process.env.ADMIN_SECRET_PASSPHRASE;
  const adminWalletsEnv = process.env.ADMIN_WALLET_ADDRESSES || "";
  const allowedWallets = adminWalletsEnv
    .split(",")
    .map((w) => w.trim().toLowerCase())
    .filter(Boolean);

  // 1. Check Passphrase
  const passphraseHeader = request.headers.get("x-admin-passphrase");
  if (!adminSecret || !passphraseHeader || passphraseHeader !== adminSecret) {
    return { authorized: false, error: "Invalid or missing admin passphrase" };
  }

  // 2. Check Wallet Header
  const walletHeader = request.headers.get("x-admin-wallet");
  if (!walletHeader) {
    return { authorized: false, error: "Missing admin wallet address" };
  }

  const walletClean = walletHeader.trim();
  if (allowedWallets.length > 0 && !allowedWallets.includes(walletClean.toLowerCase())) {
    return { authorized: false, error: "Wallet address is not authorized for admin access" };
  }

  // 3. Check Signature and Nonce
  const signatureHeader = request.headers.get("x-admin-signature");
  const nonceHeader = request.headers.get("x-admin-nonce");

  if (!signatureHeader || !nonceHeader) {
    return { authorized: false, error: "Missing cryptographic signature or nonce" };
  }

  // Verify that nonce was generated by server and is not expired
  const nonceTimestamp = activeNonces.get(nonceHeader);
  if (!nonceTimestamp || Date.now() - nonceTimestamp > NONCE_EXPIRY_MS) {
    return { authorized: false, error: "Challenge nonce is invalid or expired. Please re-authenticate." };
  }

  try {
    const messageBytes = new TextEncoder().encode(nonceHeader);
    const signatureBytes = bs58.decode(signatureHeader);
    const publicKey = new PublicKey(walletClean);
    const publicKeyBytes = publicKey.toBytes();

    const isVerified = nacl.sign.detached.verify(
      messageBytes,
      signatureBytes,
      publicKeyBytes
    );

    if (!isVerified) {
      return { authorized: false, error: "Cryptographic signature verification failed" };
    }

    // Single-use nonce: delete after successful verification
    activeNonces.delete(nonceHeader);

    return { authorized: true, wallet: walletClean };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Signature validation error";
    return { authorized: false, error: msg };
  }
}
